---
- name: Setup
  ansible.builtin.import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Setup
  ansible.builtin.import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
