---
- name: Ensure dependencies are present
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present

- name: Add Nodesource apt key
  ansible.builtin.apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  become: true

- name: Add NodeSource repositories for Node.js
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  notify: Update apt cache
  become: true

- name: Ensure Node.js and npm are installed
  ansible.builtin.apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
  become: true

- name: Install yarn
  community.general.npm:
    name: yarn
    global: yes
  become: true
