---
- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "18.20.4"
    nodejs_checksum: "sha256:ee3d14813aedf4bb165114d61d3f6424b076e7177bfadd15de1e7dfe2b52de53"
  when: nodejs_version_major | int == 18

- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "20.16.0"
    nodejs_checksum: "sha256:c6fa9b14fae46c7673ec320d34dafdc56ba12a404be308315deaa6591d59fae1"
  when: nodejs_version_major | int == 20

- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "22.6.0"
    nodejs_checksum: "sha256:ac8832bc6d879937b64e201da42f1d68fc67837ff6c359500d599dd95e2c8805"
  when: nodejs_version_major | int == 22

- name: Set artifact download URL
  ansible.builtin.set_fact:
    nodejs_download_url: "https://code.europa.eu/api/v4/projects/569/packages/generic/amazonlinux2-nodejs/{{ nodejs_release }}/nodejs-v{{ nodejs_release }}.tar.gz"
    nodejs_install_path: "/opt/nodejs/{{ nodejs_release }}"

- name: Check if Node.js {{ nodejs_version_major }} is already installed # noqa: name[template]
  ansible.builtin.stat:
    path: "{{ nodejs_install_path }}"
  register: nodejs_st

- name: Install Node.js
  when: nodejs_st.stat.isdir is not defined
  block:
  - name: Create directory
    ansible.builtin.file:
      state: directory
      owner: root
      group: root
      mode: 'u=rwx,go=rx'
      path: "{{ nodejs_install_path }}"
    become: true

  - name: Download Node.js artifact
    ansible.builtin.get_url:
      url: "{{ nodejs_download_url }}"
      checksum: "{{ nodejs_checksum }}"
      mode: 'u=rwx,go=rx'
      dest: /tmp
    register: downloaded_file

  - name: Extract artifact
    ansible.builtin.unarchive:
      src: "{{ downloaded_file.dest }}"
      dest: "{{ nodejs_install_path }}"
      owner: "root"
      group: "root"
      mode: "u=rwx,go=rx"
      remote_src: yes
      extra_opts: [--strip-components=3]
    become: true

  - name: Create node symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/node"
      dest: /usr/local/bin/node
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create npm symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/npm"
      dest: /usr/local/bin/npm
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create npx symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/npx"
      dest: /usr/local/bin/npx
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create corepack symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/corepack"
      dest: /usr/local/bin/corepack
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Clean up temporary files
    ansible.builtin.file:
      path: "{{ downloaded_file.dest }}"
      state: absent

- name: Install yarn
  community.general.npm:
    name: yarn
    global: true
    executable: /usr/local/bin/npm
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  become: true

- name: Create yarn symlink
  ansible.builtin.file:
    src: "{{ nodejs_install_path }}/bin/yarn"
    dest: /usr/local/bin/yarn
    owner: "root"
    group: "root"
    mode: 'u=rwx,go=rx'
    state: link
  become: true
