---
- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "18.20.5"
    nodejs_checksum: "sha256:5fa720a71334353f9a32214dbd67f8ee410aecaf5755050fc75565c09b6efdc9"
  when: nodejs_version_major | int == 18

- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "20.18.1"
    nodejs_checksum: "sha256:4528bf62e26983e7892799f045b96df41550696dcdc244388e1fba262cfb990b"
  when: nodejs_version_major | int == 20

- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "22.13.0"
    nodejs_checksum: "sha256:c654f3145237ce6bba06a06b6db9c094d4e56889159dd247727ca13f43d598e5"
  when: nodejs_version_major | int == 22

- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "23.6.0"
    nodejs_checksum: "sha256:4634a45a8168d2b69f2e9e720d86c3e019f7816b214f6b1622e2b039d2651b1d"
  when: nodejs_version_major | int == 23

- name: Set artifact download URL
  ansible.builtin.set_fact:
    nodejs_download_url: "https://code.europa.eu/api/v4/projects/569/packages/generic/amazonlinux2-nodejs/{{ nodejs_release }}/nodejs-v{{ nodejs_release }}.tar.gz"
    nodejs_install_path: "/opt/nodejs/{{ nodejs_release }}"

- name: Check if Node.js {{ nodejs_version_major }} is already installed # noqa: name[template]
  ansible.builtin.stat:
    path: "{{ nodejs_install_path }}"
  register: nodejs_st

- name: Install Node.js
  when: nodejs_st.stat.isdir is not defined
  block:
  - name: Create directory
    ansible.builtin.file:
      state: directory
      owner: root
      group: root
      mode: 'u=rwx,go=rx'
      path: "{{ nodejs_install_path }}"
    become: true

  - name: Download Node.js artifact
    ansible.builtin.get_url:
      url: "{{ nodejs_download_url }}"
      checksum: "{{ nodejs_checksum }}"
      mode: 'u=rwx,go=rx'
      dest: /tmp
    register: downloaded_file

  - name: Extract artifact
    ansible.builtin.unarchive:
      src: "{{ downloaded_file.dest }}"
      dest: "{{ nodejs_install_path }}"
      owner: "root"
      group: "root"
      mode: "u=rwx,go=rx"
      remote_src: yes
      extra_opts: [--strip-components=3]
    become: true

  - name: Create node symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/node"
      dest: /usr/local/bin/node
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create npm symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/npm"
      dest: /usr/local/bin/npm
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create npx symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/npx"
      dest: /usr/local/bin/npx
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create corepack symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/corepack"
      dest: /usr/local/bin/corepack
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Clean up temporary files
    ansible.builtin.file:
      path: "{{ downloaded_file.dest }}"
      state: absent

- name: Install yarn
  community.general.npm:
    name: yarn
    global: true
    executable: /usr/local/bin/npm
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  become: true

- name: Create yarn symlink
  ansible.builtin.file:
    src: "{{ nodejs_install_path }}/bin/yarn"
    dest: /usr/local/bin/yarn
    owner: "root"
    group: "root"
    mode: 'u=rwx,go=rx'
    state: link
  become: true
