---
- name: Set up the NodeSource RPM directory
  ansible.builtin.set_fact:
    rhel_distribution_major_version: 7

- name: Set up the NodeSource RPM directory
  ansible.builtin.set_fact:
    rhel_distribution_major_version: "{{ ansible_distribution_major_version }}"
  when: ansible_distribution_major_version | int >= 8

- name: Remove previous NodeSource repository files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/yum.repos.d/nodesource-{{ nodejs_version }}.repo"
    - "/etc/yum.repos.d/nodesource-nodejs-{{ nodejs_version }}.repo"
  notify: Clean yum metadata
  become: true

- name: Ensure Node.js and npm are installed
  ansible.builtin.dnf:
    name: "@nodejs:{{ nodejs_version_major }}/common"
    state: present
    allow_downgrade: true
  become: true

- name: Install yarn
  community.general.npm:
    name: yarn
    global: yes
  become: true
