---
- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "18.20.8"
    nodejs_checksum: "sha256:32ec077b440c1335d3b2b21f75eccdb7ba34f954ba0726dfd4b63bee706e54d0"
  when: nodejs_version_major | int == 18

- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "20.19.2"
    nodejs_checksum: "sha256:89faaf2341b256d1988fc4a43fb0341e80384ace067c4fe20e8a88c814042229"
  when: nodejs_version_major | int == 20

- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "22.16.0"
    nodejs_checksum: "sha256:e0fbf734def4459768055395c189157042f4ce0cb5e038b2ab679ca8b26d6b5f"
  when: nodejs_version_major | int == 22

- name: Set Node.js release
  ansible.builtin.set_fact:
    nodejs_release: "23.6.1"
    nodejs_checksum: "sha256:594450a2fb2896adf76dfcc06ef7e6637ed08f000b9290f4c175dee2fe2384a8"
  when: nodejs_version_major | int == 23

- name: Set artifact download URL
  ansible.builtin.set_fact:
    nodejs_download_url: "https://code.europa.eu/api/v4/projects/569/packages/generic/amazonlinux2-nodejs/{{ nodejs_release }}/nodejs-v{{ nodejs_release }}.tar.gz"
    nodejs_install_path: "/opt/nodejs/{{ nodejs_release }}"

- name: Check if Node.js {{ nodejs_version_major }} is already installed # noqa: name[template]
  ansible.builtin.stat:
    path: "{{ nodejs_install_path }}"
  register: nodejs_st

- name: Install Node.js
  when: nodejs_st.stat.isdir is not defined
  block:
  - name: Create directory
    ansible.builtin.file:
      state: directory
      owner: root
      group: root
      mode: 'u=rwx,go=rx'
      path: "{{ nodejs_install_path }}"
    become: true

  - name: Download Node.js artifact
    ansible.builtin.get_url:
      url: "{{ nodejs_download_url }}"
      checksum: "{{ nodejs_checksum }}"
      mode: 'u=rwx,go=rx'
      dest: /tmp
    register: downloaded_file

  - name: Extract artifact
    ansible.builtin.unarchive:
      src: "{{ downloaded_file.dest }}"
      dest: "{{ nodejs_install_path }}"
      owner: "root"
      group: "root"
      mode: "u=rwx,go=rx"
      remote_src: yes
      extra_opts: [--strip-components=3]
    become: true

  - name: Create node symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/node"
      dest: /usr/local/bin/node
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create npm symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/npm"
      dest: /usr/local/bin/npm
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create npx symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/npx"
      dest: /usr/local/bin/npx
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Create corepack symlink
    ansible.builtin.file:
      src: "{{ nodejs_install_path }}/bin/corepack"
      dest: /usr/local/bin/corepack
      owner: "root"
      group: "root"
      mode: 'u=rwx,go=rx'
      state: link
    become: true

  - name: Clean up temporary files
    ansible.builtin.file:
      path: "{{ downloaded_file.dest }}"
      state: absent

- name: Install yarn
  community.general.npm:
    name: yarn
    global: true
    executable: /usr/local/bin/npm
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  become: true

- name: Create yarn symlink
  ansible.builtin.file:
    src: "{{ nodejs_install_path }}/bin/yarn"
    dest: /usr/local/bin/yarn
    owner: "root"
    group: "root"
    mode: 'u=rwx,go=rx'
    state: link
  become: true
