---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include nodejs role
      ansible.builtin.include_role:
        name: nodejs
      vars:
        nodejs_download_url: "https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x64.tar.xz"
        nodejs_checksum: "sha256:d8dab549b09672b03356aa2257699f3de3b58c96e74eb26a8b495fbdc9cf6fbe"
        nodejs_install_path: "/opt/nodejs/20.11.1"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
