---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include nodejs role
      ansible.builtin.include_role:
        name: nodejs
      vars:
        nodejs_download_url: "https://nodejs.org/dist/v22.13.0/node-v22.13.0-linux-x64.tar.xz"
        nodejs_checksum: "sha256:3ff0d57063c33313d73d0bdcebc4c778ad6be948234584694a042c6fe57164f6"
        nodejs_install_path: "/opt/nodejs/22.13.0"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
